### PR TITLE
retry on EINTR in accept loop

### LINKED ISSUE #263: 'actix-server accept loop' panic when resuming from sleep
I don't know if this bug can affect web servers in production but I encounter it daily as a developer.

## Steps to reproduce

1. Build and launch an actix server (tested with Ubuntu 20.10).
2. Suspend the computer.
3. Resume the computer.

```log
thread 'actix-server accept loop' panicked at 'Poll error: Interrupted system call (os error 4)', /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:164:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: actix_server::accept::Accept::poll_with::{{closure}}
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:164
   3: core::result::Result<T,E>::unwrap_or_else
             at /home/yoric/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:825
   4: actix_server::accept::Accept::poll_with
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:162
   5: actix_server::accept::Accept::start::{{closure}}
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:114
```

While the situation in which a server goes to sleep is unusual, I can think of applications that embed a web server for use on a desktop/laptop, which makes it a potential issue for some apps.

## Expected Behavior

The web server should be able to somehow resume activity when the computer wakes up.

## Your Environment

* Rust Version (I.e, output of `rustc -V`):1.48
* Actix Web Version: 2.0.0-beta.2

### PR DESCRIPTION
**Pull request by shuoli84**
## PR Type

Bug Fix

## PR Checklist
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

Currently, EINTR which equals std::io::ErrorKind::Interrupted will trigger a panic. This change captures it and retry poll. 

closes #263

### CODE REVIEW

File: actix-server/src/accept.rs [hunk 1]
```diff
@@ -161,9 +161,13 @@ impl Accept {
...
         loop {
-            self.poll
-                .poll(&mut events, None)
-                .unwrap_or_else(|e| panic!("Poll error: {}", e));
+            if let Err(e) = self.poll.poll(&mut events, None) {
+                if matches!(e.kind(), std::io::ErrorKind::Interrupted) {
+                    continue;
+                } else {
+                    panic!("Poll error: {}", e);
+                }
```
Comment (robjtede) [inline actix-server/src/accept.rs:169]: would prefer a plain match style

**Review by robjtede — CHANGES_REQUESTED** [review]
Thanks for the change. Can you add a changelog entry. No testing required for this.

File: actix-server/src/accept.rs (hunk 1 above)
Comment (shuoli84) [reply actix-server/src/accept.rs]: Updated

**Review by robjtede — APPROVED** [review]
nice, thanks 👍🏻
